---
swagger: "2.0"
info:
  description: "File accessibilty checker.  Accepts a file and returns accessiblity\
    \ information about the file."
  version: "0.0.1"
  title: "Accessibility Checker"
  contact:
    email: "aruethe2@swarthmore.edu"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/v1"
tags:
- name: "file"
  description: "File information"
schemes:
- "http"
paths:
  /file:
    post:
      tags:
      - "file"
      summary: "Submit a file for checking"
      description: ""
      operationId: "scanFile"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "upfile"
        in: "formData"
        description: "The file to scan"
        required: true
        type: "file"
      - name: "maxPages"
        in: "formData"
        description: "Override the default maximum number of pages to scan"
        required: false
        type: "integer"
      - name: "id"
        in: "formData"
        description: "Optional id number to associate with the file"
        required: false
        type: "string"
      responses:
        200:
          description: "A scan response"
          schema:
            $ref: "#/definitions/inline_response_200_1"
        400:
          description: "Invalid status value"
        422:
          description: "Cannot process file: filetype, file error, or security problem."
      x-swagger-router-controller: "File"
  /url:
    get:
      tags:
      - "url"
      summary: "Submit a URL for checking"
      description: ""
      operationId: "scanUrl"
      produces:
      - "application/json"
      parameters:
      - name: "url"
        in: "query"
        description: "The url to scan"
        required: true
        type: "string"
        pattern: "https?://.+"
      - name: "maxPages"
        in: "query"
        description: "Override the default maximum number of pages to scan"
        required: false
        type: "integer"
      - name: "id"
        in: "query"
        description: "Optional id number to associate with the file"
        required: false
        type: "string"
      responses:
        200:
          description: "A scan response"
          schema:
            $ref: "#/definitions/inline_response_200_1"
        400:
          description: "Invalid status value"
        422:
          description: "Cannot process file: filetype, file error, or security problem."
      x-swagger-router-controller: "File"
definitions:
  inline_response_200:
    properties:
      filename:
        type: "string"
        description: "the filename"
      id:
        type: "string"
        description: "id number (if provided)"
      hasText:
        type: "boolean"
        description: "does the file contain text"
      pages:
        type: "integer"
        description: "number of pages in document"
  inline_response_200_1:
    properties:
      filename:
        type: "string"
        description: "the filename"
      id:
        type: "string"
        description: "id number (if provided)"
      hasText:
        type: "boolean"
        description: "does the file contain text"
      pages:
        type: "integer"
        description: "number of pages in document"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
